{
 "title": "Core Metrics for Infra Mgmt",
 "description": "for collectd monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "100 - collectd_cpu_percent{type=\"idle\"}"
    }
   ]
  },
  {
   "title": "Uncorrected Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(collectd_mcelog_errors{type=\"uncorrected_memory_errors\"}) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{memory=\"used\"})\n"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " collectd_interface_if_packets_rx {interface=\"enp61s0f0\"}",
     "legendFormat": "Receive"
    },
    {
     "expr": "collectd_interface_if_packets_tx {interface=\"enp61s0f0\"}",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_disk_io_time_weighted_io_time)"
    }
   ]
  },
  {
   "title": "SMART DISK - ENDURANCE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Endurance %" }
   ],
   "targets": [
    {
     "expr": "collectd_smart_attribute_worst {type=\"endurance-remaining\"}",
     "legendFormat": "{{smart}}"
    }
   ]
  },
  { "title": "Alert Panel", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 } },
  {
   "title": "MCELOG Error Volume",
   "type": "graph",
   "description": "Uncorrectable errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_mcelog_errors{type=\"corrected_memory_errors_in_24h\"}  "
    }
   ]
  },
  {
   "title": "MCE LOG",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "collectd_mcelog_errors  {type=\"corrected_memory_errors\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collectd_load_0\n\n" },
    { "expr": "collectd_load_1" },
    { "expr": "collectd_load_2" }
   ]
  },
  {
   "title": "IPMI Airflow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collectd_ipmi_flow" }
   ]
  },
  {
   "title": "Numa",
   "type": "graph",
   "description": "Hit, Miss, Foreign",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_numa_vmpage_action {type=\"numa_miss\"}"
    },
    {
     "expr": "collectd_numa_vmpage_action {type=\"numa_foreign\"}"
    },
    {
     "expr": "collectd_numa_vmpage_action {type=\"numa_hit\"}"
    }
   ]
  },
  {
   "title": "Intel PMU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_intel_pmu_counter_total"
    }
   ]
  }
 ]
}