{
 "title": "OTP - ELG Ingestion",
 "time": { "from": "2020-02-10T19:58:51.928Z", "to": "2020-02-11T21:03:53.494Z" },
 "panels": [
  { "title": "PERF Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_CPU utilization %",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cycles per Instruction",
   "type": "graph",
   "description": "~ 1 is good, greater than 2 is not desirable.   ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:120",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:121",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:118",
       "field": "metric_CPI",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU Frequency",
   "type": "graph",
   "description": "Important to know SKU, compare Frequency of SKU against run rate. ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 2, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_CPU operating frequency (in GHz)",
       "id": "1",
       "inlineScript": "_value * 1000000000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000000000" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Utilization in Kernel",
   "type": "graph",
   "description": "If anything beyond 10% in metric cpu utilization in kernel need to investigate.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_CPU utilization% in kernel mode",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Read Bandwidth (MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_memory bandwidth read (MB/sec)",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Write Bandwidth (MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_memory bandwidth write (MB/sec)",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Total Bandwidth (MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_memory bandwidth total (MB/sec)",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Local NUMA Reads %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_NUMA %_Reads addressed to local DRAM",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Remote NUMA Reads %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_NUMA %_Reads addressed to remote DRAM",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "LLC Miss Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_Average LLC data read miss latency (in ns)",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Package Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric_package power (watts)",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "DSTAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Memory % Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory usage % free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory % Buffered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory usage % buff",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory % Cached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory usage % cach",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory % Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory usage % used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Throughput (MB/s) Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "network throughput (MB/s) recv",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Throughput (MB/s) Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "network throughput (MB/s) send",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Throughput (MB/s) Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "disk throughput (MB/s) read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Throughput (MB/s) Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "disk throughput (MB/s) writ",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IOPS Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "IOPS read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "IOPS writ",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Context Switches/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system Context Switches/Second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interrupts/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "60" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system Interrupts/Second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "IPMI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CUPs Index",
   "type": "graph",
   "description": "CUPS is a representation of aggregate physical utilization of the three fundamental compute resources within a server platform, viz. the processor, memory and IO subsystems, respectively. CUPS is expressed as a percentage of maximum compute headroom (in resource usage per second) for a given power and thermal budget.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metric_name=\"CUPs Index\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metric_name=\"System Power in [Watts]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metric_name=\"CPU Power in [Watts]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "value=\"CPU #0\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "value=\"CPU #1\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Inlet Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metric_name=\"Inlet Temp in [Celsius]\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}