{
 "title": "Core Metrics for Infra Mgmt",
 "description": "for collectd monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NS",
    "label": "项目",
    "query": "label_values(container_cpu_cfs_periods_total, namespace)"
   },
   {
    "name": "POD",
    "label": "容器名称",
    "query": "label_values(container_memory_usage_bytes{container_name=~\"etcd|mysql|vtctld|vttablet\",namespace=\"$NS\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{memory=\"used\"})\n"
    }
   ]
  },
  {
   "title": "SMART DISK - ENDURANCE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Endurance %" }
   ],
   "targets": [
    {
     "expr": "collectd_smart_attribute_worst {type=\"endurance-remaining\"}",
     "legendFormat": "{{smart}}"
    }
   ]
  },
  {
   "title": "CPU usage - sum of negative idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "100 - collectd_cpu_percent{type=\"idle\"}"
    }
   ]
  },
  {
   "title": "Finding DISK LOVE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "collectd_disk_io_time_0" },
    { "expr": "collectd_disk_ops_1" },
    { "expr": "collectd_disk_time_0" },
    { "expr": "collectd_disk_time_1" },
    { "expr": "collectd_disk_io_time_0" },
    { "expr": "collectd_disk_io_time_1" },
    {}
   ]
  }
 ]
}