{
 "title": "monitoring metrics show graph",
 "description": "for jed monitoring only",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NS",
    "label": "项目",
    "query": "label_values(container_cpu_cfs_periods_total, namespace)"
   },
   {
    "name": "POD",
    "label": "容器名称",
    "query": "label_values(container_memory_usage_bytes{container_name=~\"etcd|mysql|vtctld|vttablet\",namespace=\"$NS\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{memory=\"used\"})\n"
    }
   ]
  },
  {
   "title": "CPU usage - sum of negative idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "100 - sum(collectd_cpu{type=\"idle\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Finding DISK LOVE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "collectd_disk_ops_0", "legendFormat": "{{pod_name}}" },
    { "expr": "collectd_disk_ops_1" },
    { "expr": "collectd_disk_time_0" },
    { "expr": "collectd_disk_time_1" },
    { "expr": "collectd_disk_io_time_0" },
    { "expr": "collectd_disk_io_time_1" },
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "核数" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu{type=\"idle\"})\n\n\n"
    }
   ]
  },
  {
   "title": "Mysql-CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "单核" }
   ],
   "targets": [
    { "expr": "collectd_load_1", "legendFormat": "{{pod_name}}" }
   ]
  },
  {
   "title": "Tablet-CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "cpu core  " }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$NS\", pod_name=~\"^$POD$\",container_name=\"vttablet\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "POD Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps", "label": "核数" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$NS\", pod_name=~\"^$POD$\"}[1m])) by (pod_name)",
     "legendFormat": "-> flow  input"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$NS\", pod_name=~\"^$POD$\"}[1m])) by (pod_name)",
     "legendFormat": "<- flow output"
    }
   ]
  }
 ]
}